/// Flutter icons ChatAPP_Icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChatAPP_Icons
///      fonts:
///       - asset: fonts/ChatAPP_Icons.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ChatAPP_Icons {
  ChatAPP_Icons._();

  static const _kFontFam = 'ChatAPP_Icons';
  static const String? _kFontPkg = null;

  static const IconData emo_happy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_unhappy = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sleep = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_thumbsup = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_devil = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_surprised = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_tongue = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_coffee = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sunglasses = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_displeased = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_beer = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_grin = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_angry = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_saint = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_cry = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_shoot = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_squint = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_laugh = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData install = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_outline = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large_outline = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list_outline = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_1 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_outline = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_station = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poop = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_2 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_2 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_1 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_inv = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list_1 = IconData(0xf009, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb = IconData(0xf00a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb_empty = IconData(0xf00b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_alt = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_empty = IconData(0xf0e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_left = IconData(0xf100, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_left = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xf109, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = IconData(0xf10a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child = IconData(0xf1ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xf1d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_empty = IconData(0xf1d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = IconData(0xf1f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off_empty = IconData(0xf1f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xf4ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_ninja = IconData(0xf504, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
